# marekvs — all project commands. Run `just` for the menu.

set shell := ["bash", "-cu"]

image      := "marekvs:dev"
compose    := "deploy/compose.yaml"
k8s_dir    := "k8s"
# override to build against a different ondadb checkout (e.g. a clean clone
# while the sibling tree is mid-edit): ONDADB_DIR=/path just build
ondadb_dir := env_var_or_default("ONDADB_DIR", "../ondadb")

# ── ANSI palette ─────────────────────────────────────────────────────────
reset  := '\033[0m'
bold   := '\033[1m'
dim    := '\033[2m'
red    := '\033[31m'
green  := '\033[32m'
yellow := '\033[33m'
blue   := '\033[34m'
purple := '\033[35m'
cyan   := '\033[36m'

# colorful command menu (also: `just --list`)
[private]
default:
    @printf '{{bold}}{{purple}}\n  ┌─────────────────────────────────────────────────┐\n'
    @printf '  │  marekvs — distributed Redis-compatible KV      │\n'
    @printf '  │  AP · disk-native (ondadb) · Kubernetes-native  │\n'
    @printf '  └─────────────────────────────────────────────────┘{{reset}}\n\n'
    @just --list --unsorted --list-heading '' --color always
    @printf '\n{{dim}}docs: design/README.md · k8s example: k8s/README.md{{reset}}\n'

# ══ build ════════════════════════════════════════════════════════════════

# ondadb comes from git (Cargo.toml) unless a sibling checkout exists at
# ../ondadb, in which case a [patch] in .cargo/config.toml redirects to it.
# Regenerated before every build so the state always matches reality.
[private]
_cargo-config:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p .cargo
    if [ -d "{{ondadb_dir}}" ]; then
        printf '# generated by `just _cargo-config` — do not edit, gitignored\n[patch."https://github.com/yannick/ondadb.git"]\nondadb = { path = "%s" }\n' "$(cd "{{ondadb_dir}}" && pwd)" > .cargo/config.toml
    else
        rm -f .cargo/config.toml
    fi

# debug build of the whole workspace
[group('build')]
build: _cargo-config
    @printf '{{bold}}{{blue}}▸ building workspace (debug){{reset}}\n'
    cargo build --workspace

# optimized release build
[group('build')]
release: _cargo-config
    @printf '{{bold}}{{blue}}▸ building workspace (release){{reset}}\n'
    cargo build --workspace --release

# type-check quickly without codegen
[group('build')]
check: _cargo-config
    cargo check --workspace --all-targets

# ══ quality ══════════════════════════════════════════════════════════════

# auto-format all crates (rustfmt)
[group('quality')]
fmt:
    cargo fmt --all

# verify formatting without changing files (CI mode)
[group('quality')]
fmt-check:
    cargo fmt --all --check

# lint the whole workspace; warnings are errors
[group('quality')]
clippy:
    cargo clippy --workspace --all-targets -- -D warnings

# fmt-check + clippy + tests + grudge-topology self-test: the CI gate
[group('quality')]
ci: fmt-check clippy test grudge-test
    @printf '{{bold}}{{green}}✓ CI gate passed{{reset}}\n'

# ══ test ═════════════════════════════════════════════════════════════════

# unit + integration tests for all crates
[group('test')]
test: _cargo-config
    cargo test --workspace

# merge-law property tests only (design/10 §10.1)
[group('test')]
test-merge:
    cargo test -p marekvs-core --test merge_laws

# single-node end-to-end smoke test via redis-cli against a local server
[group('test')]
test-smoke: build
    ./tests/smoke.sh target/debug/marekvs-server

# REPLICAOF: follow a real redis master (redis-server, or redis in docker)
[group('test')]
test-replicaof: build
    ./tests/replicaof.sh target/debug/marekvs-server

# ══ run ══════════════════════════════════════════════════════════════════

# run a single local node — RESP :6379, metrics :9121 (data ./.data/n0)
[group('run')]
run *ARGS:
    MAREKVS_DATA_DIR=.data/n0 cargo run -p marekvs-server -- {{ARGS}}

# run a local 3-node cluster, ctrl-c stops all — RESP 6379/6380/6381, metrics 9121-9123
[group('run')]
run-cluster: build
    ./tests/local_cluster.sh target/debug/marekvs-server 3

# ══ docker ═══════════════════════════════════════════════════════════════

# Stage a clean build context containing marekvs + the ondadb sibling, with
# the [patch] config so the container build uses the copied ondadb.
[private]
_stage-ctx:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ ! -d "{{ondadb_dir}}" ]; then
        echo "error: image builds need an ondadb checkout (ONDADB_DIR or ../ondadb):" >&2
        echo "  git clone https://github.com/yannick/ondadb.git ../ondadb" >&2
        exit 1
    fi
    rm -rf .build-ctx && mkdir -p .build-ctx/marekvs/.cargo
    rsync -a --exclude target --exclude .git "{{ondadb_dir}}/" .build-ctx/ondadb/
    rsync -a --exclude target --exclude .git --exclude .data --exclude .build-ctx ./ .build-ctx/marekvs/
    printf '[patch."https://github.com/yannick/ondadb.git"]\nondadb = { path = "../ondadb" }\n' > .build-ctx/marekvs/.cargo/config.toml

# build the FROM-scratch image (native arch)
[group('docker')]
docker-build: _stage-ctx
    @printf '{{bold}}{{cyan}}▸ docker build → {{image}}{{reset}}\n'
    docker build -f .build-ctx/marekvs/Dockerfile -t {{image}} .build-ctx

# start a 3-node docker compose cluster — RESP on host 16379/16380/16381
[group('docker')]
docker-up:
    ./tests/preflight.sh 16379 16380 16381
    docker compose -f {{compose}} up -d --build
    ./tests/wait_ready.sh localhost 16379 16380 16381

# stop the compose cluster and delete its volumes
[group('docker')]
docker-down:
    docker compose -f {{compose}} down -v

# convergence + replication tests against the compose cluster
# (teardown runs even on failure — a leftover cluster leaks counter state
# into the next run and every assertion inherits garbage)
[group('docker')]
docker-test: docker-up
    #!/usr/bin/env bash
    set -euo pipefail
    trap 'just docker-down' EXIT
    ./tests/cluster_test.sh localhost 16379 16380 16381
    printf '{{bold}}{{green}}✓ docker cluster test passed{{reset}}\n'

# ══ apple containers ═════════════════════════════════════════════════════

# build the image with Apple's `container` CLI
[group('apple')]
apple-build: _stage-ctx
    container system start || true
    container build -f .build-ctx/marekvs/Dockerfile -t {{image}} .build-ctx

# start a 3-node apple-container cluster — each node on its container IP :6379 / :9121 (no host ports)
[group('apple')]
apple-up: apple-build
    ./tests/apple_cluster.sh up {{image}}

# stop and remove the apple-container cluster
[group('apple')]
apple-down:
    ./tests/apple_cluster.sh down

# convergence + replication tests against the apple-container cluster
# (teardown runs even on failure, same reasoning as docker-test)
[group('apple')]
apple-test: apple-up
    #!/usr/bin/env bash
    set -euo pipefail
    trap './tests/apple_cluster.sh down' EXIT
    ./tests/apple_cluster.sh test
    printf '{{bold}}{{green}}✓ apple cluster test passed{{reset}}\n'

# ══ chaos (Jepsen-style fault injection) ═════════════════════════════════

# full chaos+churn suite on docker: crashes, TRUE partitions, freezes,
# rolling churn, wipe-replace, membership churn, bank conservation
[group('chaos')]
chaos-docker: docker-build
    #!/usr/bin/env bash
    set -euo pipefail
    trap 'BACKEND=docker bash -c "source tests/chaos/lib.sh; cluster_down"' EXIT
    BACKEND=docker ./tests/chaos/chaos_test.sh
    printf '{{bold}}{{green}}✓ docker chaos suite passed{{reset}}\n'

# chaos suite on apple containers: per-VM clocks (real skew!); partitions
# are skipped (no runtime network detach)
[group('chaos')]
chaos-apple: apple-build
    #!/usr/bin/env bash
    set -euo pipefail
    trap 'BACKEND=apple bash -c "source tests/chaos/lib.sh; cluster_down"' EXIT
    BACKEND=apple ./tests/chaos/chaos_test.sh
    printf '{{bold}}{{green}}✓ apple chaos suite passed{{reset}}\n'

# run selected scenarios only, e.g. `just chaos partition_divergence bank`
[group('chaos')]
chaos +scenarios: docker-build
    BACKEND=docker ./tests/chaos/chaos_test.sh {{scenarios}}

# build the DEBUG image (same binary, alpine userland + iptables/tc/date)
[group('chaos')]
debug-build: _stage-ctx
    docker build -f .build-ctx/marekvs/Dockerfile.debug -t marekvs:debug .build-ctx

# build the debug image with Apple's container CLI
[group('chaos')]
debug-apple-build: _stage-ctx
    container system start || true
    container build -f .build-ctx/marekvs/Dockerfile.debug -t marekvs:debug .build-ctx

# privileged-fault suite on docker: grudge partitions (bridge, majority
# ring) + tc-netem packet faults. Needs the debug image + NET_ADMIN.
[group('chaos')]
chaos-debug: debug-build
    #!/usr/bin/env bash
    set -euo pipefail
    trap 'CHAOS_DEBUG=1 BACKEND=docker bash -c "source tests/chaos/lib.sh; cluster_down"' EXIT
    CHAOS_DEBUG=1 BACKEND=docker ./tests/chaos/chaos_test.sh bridge_partition majority_ring slow_peer lossy_writes blackhole_conn backpressure_no_drop
    printf '{{bold}}{{green}}✓ debug fault suite passed{{reset}}\n'

# clock-fault suite on apple containers (per-VM clocks): bump + strobe
[group('chaos')]
chaos-clock: debug-apple-build
    #!/usr/bin/env bash
    set -euo pipefail
    trap 'CHAOS_DEBUG=1 BACKEND=apple bash -c "source tests/chaos/lib.sh; cluster_down"' EXIT
    CHAOS_DEBUG=1 BACKEND=apple ./tests/chaos/chaos_test.sh clock_bump_skew clock_strobe
    printf '{{bold}}{{green}}✓ clock fault suite passed{{reset}}\n'

# self-test the pure grudge topology builders (no cluster needed)
[group('chaos')]
grudge-test:
    python3 tests/chaos/grudge.py --test

# Docker host ports — RESP 26379/26380/26381, metrics 27121/27122/27123.
# Apple: no host ports; connect on each container IP :6379 / :9121 (printed
# by the recipe). Debug image (grudge/netem tools; NET_ADMIN+SYS_TIME).
# start a 3-node debug cluster and leave it running (`just chaos-down` to stop)
[group('chaos')]
chaos-up backend="docker": (_chaos-img backend)
    #!/usr/bin/env bash
    set -euo pipefail
    CHAOS_DEBUG=1 BACKEND={{backend}} bash -c 'source tests/chaos/lib.sh; cluster_up'
    if [ "{{backend}}" = docker ]; then
        printf '{{bold}}{{green}}debug cluster up{{reset}} — redis-cli -p 26379|26380|26381 · metrics :27121-27123\n'
    else
        CHAOS_DEBUG=1 BACKEND=apple bash -c 'source tests/chaos/lib.sh
        for i in 0 1 2; do echo "  chaos-$i: $(apple_ip chaos-$i):6379 (metrics :9121)"; done'
    fi

# stop the running debug cluster and sweep any stray marekvs containers
[group('chaos')]
chaos-down backend="docker":
    CHAOS_DEBUG=1 BACKEND={{backend}} bash -c 'source tests/chaos/lib.sh; cluster_down'
    @printf '{{dim}}debug cluster stopped (stray marekvs containers swept){{reset}}\n'

# show the running debug cluster's containers + published ports
[group('chaos')]
chaos-status backend="docker":
    #!/usr/bin/env bash
    if [ "{{backend}}" = docker ]; then
        # default columns already include NAMES / PORTS / STATUS (a Go
        # --format template would be mangled by just interpolation)
        docker ps --filter ancestor=marekvs:debug
    else
        container ls 2>/dev/null | awk 'NR==1 || /marekvs:debug/'
    fi

# pick the right debug image build for the backend (internal)
[private]
_chaos-img backend:
    #!/usr/bin/env bash
    if [ "{{backend}}" = docker ]; then just debug-build; else just debug-apple-build; fi

# ══ kubernetes ═══════════════════════════════════════════════════════════

# apply the example deployment from k8s/ (see k8s/README.md)
[group('kubernetes')]
k8s-apply:
    kubectl apply -k {{k8s_dir}}

# pods, PVCs and replication health of the running deployment
[group('kubernetes')]
k8s-status:
    kubectl get statefulset,pods,pvc -l app=marekvs
    @printf '{{dim}}replication health — 0 means fully replicated:{{reset}}\n'
    -kubectl run marekvs-probe --rm -i --restart=Never --quiet --image=curlimages/curl -- \
        -s http://marekvs-0.marekvs-headless:9121/metrics \
        | grep -E '^marekvs_cluster_(underreplicated_partitions|effective_rf_min|members)'

# scale the cluster to N nodes (data-safe; see k8s/README.md for the rules)
[group('kubernetes')]
k8s-scale n:
    kubectl scale statefulset marekvs --replicas={{n}}

# delete the example deployment (keeps PVCs — data survives)
[group('kubernetes')]
k8s-delete:
    kubectl delete -k {{k8s_dir}}
    @printf '{{yellow}}PVCs kept. To destroy data: kubectl delete pvc -l app=marekvs{{reset}}\n'

# regenerate k8s/operator/crd.yaml from the Rust types
[group('kubernetes')]
operator-crd:
    cargo run -q -p marekvs-operator -- crd > {{k8s_dir}}/operator/crd.yaml
    @printf '{{bold}}{{green}}✓ {{k8s_dir}}/operator/crd.yaml regenerated{{reset}}\n'

# install the operator (CRD + RBAC + deployment); example CR: k8s/operator/example-cluster.yaml
[group('kubernetes')]
operator-apply:
    kubectl apply -k {{k8s_dir}}/operator

# remove the operator; NOTE: deleting the CRD deletes all MarekvsClusters!
[group('kubernetes')]
operator-delete:
    kubectl delete -k {{k8s_dir}}/operator

# ══ bench (marekvs vs KeyDB) ═════════════════════════════════════════════

bench_requests := env_var_or_default("BENCH_REQUESTS", "20000")

# start the bench engines in docker — marekvs host :16391, KeyDB :16390
[group('bench')]
bench-up: docker-build
    ./tests/preflight.sh 16390 16391
    docker run -d --rm --name bench-keydb -p 16390:6379 eqalpha/keydb:latest \
        keydb-server --server-threads 4 --appendonly no
    docker run -d --rm --name bench-marekvs -p 16391:6379 \
        -e MAREKVS_NODE_ID=0 -e MAREKVS_REPLICAS_N=1 \
        -e MAREKVS_DATA_DIR=/data -e RUST_LOG=warn \
        -v bench-marekvs-data:/data {{image}}
    ./tests/wait_ready.sh localhost 16390 16391

# stop both bench engines and delete the bench volume
[group('bench')]
bench-down:
    docker rm -f bench-keydb bench-marekvs 2>/dev/null || true
    docker volume rm bench-marekvs-data 2>/dev/null || true

# run the workload matrix on both engines, then render the report
# (bench-down always runs; a leftover engine skews the next campaign)
[group('bench')]
bench: bench-up
    #!/usr/bin/env bash
    set -euo pipefail
    trap 'just bench-down' EXIT
    ./tests/preflight.sh
    mkdir -p bench
    ./bench/run_workloads.sh keydb   localhost 16390 {{bench_requests}} >> bench/results.csv
    ./bench/run_workloads.sh marekvs localhost 16391 {{bench_requests}} >> bench/results.csv
    just bench-report

# re-render bench/report.md from accumulated bench/results.csv
[group('bench')]
bench-report:
    python3 bench/report.py bench/results.csv bench/report.md
    @printf '{{bold}}{{green}}✓ report → bench/report.md{{reset}}\n'

# wipe accumulated results before a fresh campaign
[group('bench')]
bench-clean:
    rm -f bench/results.csv bench/report.md

# ══ docs site ════════════════════════════════════════════════════════════

# build the documentation website from docs/*.md → _site/
[group('docs')]
docs:
    @printf '{{bold}}{{cyan}}▸ building docs site → _site{{reset}}\n'
    cargo run --manifest-path crates/docsgen/Cargo.toml --release
    @printf '{{bold}}{{green}}✓ open _site/index.html (or `just docs-serve`){{reset}}\n'

# build the docs site and serve it at http://localhost:8791
[group('docs')]
docs-serve: docs
    @printf '{{bold}}{{blue}}▸ serving _site on http://localhost:8791{{reset}}\n'
    python3 -m http.server 8791 --directory _site --bind 127.0.0.1

# ══ housekeeping ═════════════════════════════════════════════════════════

# remove build artifacts and local run data
[group('housekeeping')]
clean:
    cargo clean
    rm -rf .data

# wipe local run data only (keeps compiled artifacts)
[group('housekeeping')]
clean-data:
    rm -rf .data
