# marekvs — all project commands. `just --list` for overview.

set shell := ["bash", "-cu"]

image   := "marekvs:dev"
compose := "deploy/compose.yaml"

default:
    @just --list

# ── ondadb source selection ──────────────────────────────────────────────

# ondadb comes from git (Cargo.toml) unless a sibling checkout exists at
# ../ondadb, in which case a [patch] in .cargo/config.toml redirects to it.
# Regenerated before every build so the state always matches reality.
_cargo-config:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p .cargo
    if [ -d ../ondadb ]; then
        printf '# generated by `just _cargo-config` — do not edit, gitignored\n[patch."https://github.com/yannick/ondadb.git"]\nondadb = { path = "../ondadb" }\n' > .cargo/config.toml
    else
        rm -f .cargo/config.toml
    fi

# ── build ────────────────────────────────────────────────────────────────

# debug build of the whole workspace
build: _cargo-config
    cargo build --workspace

# optimized release build
release: _cargo-config
    cargo build --workspace --release

# type-check quickly without codegen
check: _cargo-config
    cargo check --workspace --all-targets

# ── quality ──────────────────────────────────────────────────────────────

fmt:
    cargo fmt --all

fmt-check:
    cargo fmt --all --check

clippy:
    cargo clippy --workspace --all-targets -- -D warnings

# fmt-check + clippy + tests: the CI gate
ci: fmt-check clippy test

# ── test ─────────────────────────────────────────────────────────────────

# unit + integration tests for all crates
test: _cargo-config
    cargo test --workspace

# merge-law property tests only (design/10 §10.1)
test-merge:
    cargo test -p marekvs-core --test merge_laws

# single-node end-to-end smoke test via redis-cli against a local server
test-smoke: build
    ./tests/smoke.sh target/debug/marekvs-server

# REPLICAOF: follow a real redis master (redis-server, or redis in docker)
test-replicaof: build
    ./tests/replicaof.sh target/debug/marekvs-server

# ── run ──────────────────────────────────────────────────────────────────

# run a single local node (data in ./.data/n0)
run *ARGS:
    MAREKVS_DATA_DIR=.data/n0 cargo run -p marekvs-server -- {{ARGS}}

# run a local 3-node cluster on ports 6379/6380/6381 (foreground, ctrl-c stops all)
run-cluster: build
    ./tests/local_cluster.sh target/debug/marekvs-server 3

# ── docker ───────────────────────────────────────────────────────────────

# Stage a clean build context containing marekvs + the ondadb sibling.
# The staged tree always gets the [patch] config so the container build uses
# the copied ondadb and never needs git credentials (the repo is private).
_stage-ctx:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ ! -d ../ondadb ]; then
        echo "error: image builds need the ondadb sibling checkout:" >&2
        echo "  git clone https://github.com/yannick/ondadb.git ../ondadb" >&2
        exit 1
    fi
    rm -rf .build-ctx && mkdir -p .build-ctx/marekvs/.cargo
    rsync -a --exclude target --exclude .git ../ondadb .build-ctx/
    rsync -a --exclude target --exclude .git --exclude .data --exclude .build-ctx ./ .build-ctx/marekvs/
    printf '[patch."https://github.com/yannick/ondadb.git"]\nondadb = { path = "../ondadb" }\n' > .build-ctx/marekvs/.cargo/config.toml

# build the FROM-scratch image (native arch)
docker-build: _stage-ctx
    docker build -f .build-ctx/marekvs/Dockerfile -t {{image}} .build-ctx

# 3-node cluster via docker compose
docker-up:
    docker compose -f {{compose}} up -d --build
    ./tests/wait_ready.sh localhost 16379 16380 16381

docker-down:
    docker compose -f {{compose}} down -v

# smoke + convergence tests against the compose cluster
docker-test: docker-up
    ./tests/cluster_test.sh localhost 16379 16380 16381
    just docker-down

# ── apple containers (container CLI) ─────────────────────────────────────

# build the image with Apple's container CLI
apple-build: _stage-ctx
    container system start || true
    container build -f .build-ctx/marekvs/Dockerfile -t {{image}} .build-ctx

# 3-node cluster using apple containers
apple-up: apple-build
    ./tests/apple_cluster.sh up {{image}}

apple-down:
    ./tests/apple_cluster.sh down

# smoke + convergence tests against the apple-container cluster
apple-test: apple-up
    ./tests/apple_cluster.sh test
    just apple-down

# ── benchmarks (marekvs vs KeyDB) ────────────────────────────────────────

bench_requests := env_var_or_default("BENCH_REQUESTS", "20000")

# start both engines in docker (marekvs :16391, keydb :16390)
bench-up: docker-build
    docker run -d --rm --name bench-keydb -p 16390:6379 eqalpha/keydb:latest \
        keydb-server --server-threads 4 --appendonly no
    docker run -d --rm --name bench-marekvs -p 16391:6379 \
        -e MAREKVS_NODE_ID=0 -e MAREKVS_REPLICAS_N=1 \
        -e MAREKVS_DATA_DIR=/data -e RUST_LOG=warn \
        -v bench-marekvs-data:/data {{image}}
    ./tests/wait_ready.sh localhost 16390 16391

bench-down:
    docker rm -f bench-keydb bench-marekvs 2>/dev/null || true
    docker volume rm bench-marekvs-data 2>/dev/null || true

# run the workload matrix on both engines, then render the report
bench: bench-up
    mkdir -p bench
    ./bench/run_workloads.sh keydb   localhost 16390 {{bench_requests}} >> bench/results.csv
    ./bench/run_workloads.sh marekvs localhost 16391 {{bench_requests}} >> bench/results.csv
    just bench-down
    just bench-report

# re-render bench/report.md from accumulated bench/results.csv
bench-report:
    python3 bench/report.py bench/results.csv bench/report.md

# wipe accumulated results before a fresh campaign
bench-clean:
    rm -f bench/results.csv bench/report.md

# ── misc ─────────────────────────────────────────────────────────────────

clean:
    cargo clean
    rm -rf .data

# wipe local run data only
clean-data:
    rm -rf .data
